version: '2'
services:
  etcd:
    image: quay.io/coreos/etcd:v2.3.6
    container_name: etcd
    ports: ["4001:4001", "2380:2380", "2379:2379"]
    command:
      - -name=etcd0
      # - -listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001
      # - -listen-peer-urls=http://0.0.0.0:2380
      # - -initial-cluster-token=etcd-cluster-1
      # - -initial-cluster-state=new

      # - -advertise-client-urls=http://${HOST_IP}:2379,http://${HOST_IP}:4001
      # - -initial-advertise-peer-urls=http://${HOST_IP}:2380
      # - -initial-cluster=etcd0=http://${HOST_IP}:2380
  etcdctl:
    build: etcdctl
    container_name: etcdctl
